formWid: ''
address: 江苏省徐州市铜山区行健西路
collectWid: ''
schoolTaskWid: ''
form:
  - wid: '33782'
    formWid: '2222'
    fieldType: '2'
    title: 你的学生类别
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 1
    colName: field001
    fieldItems:
      - itemWid: '78244'
        content: 本科生
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 1
    value: '78244'
    show: true
    formType: '0'
    sortNum: '1'
    logicShowConfig: {}
  - wid: '33783'
    formWid: '2222'
    fieldType: '2'
    title: "你的生源地\_"
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 2
    colName: field002
    fieldItems:
      - itemWid: '78247'
        content: 内地
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 2
    value: '78247'
    show: true
    formType: '0'
    sortNum: '2'
    logicShowConfig: {}
  - wid: '33784'
    formWid: '2222'
    fieldType: '2'
    title: 你今天晨检体温是多少
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 3
    colName: field003
    fieldItems:
      - itemWid: '78250'
        content: 36~37.2℃（正常体温）
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 3
    value: '78250'
    show: true
    formType: '0'
    sortNum: '3'
    logicShowConfig: {}
  - wid: '33785'
    formWid: '2222'
    fieldType: '2'
    title: 你今天午检体温是多少
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 4
    colName: field004
    fieldItems:
      - itemWid: '78253'
        content: 36~37.2℃（正常体温）
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 4
    value: '78253'
    show: true
    formType: '0'
    sortNum: '4'
    logicShowConfig: {}
  - wid: '33786'
    formWid: '2222'
    fieldType: '2'
    title: 你今天是为疑似/确诊新冠肺炎患者？
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 5
    colName: field005
    fieldItems:
      - itemWid: '78256'
        content: 否
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 5
    value: '78256'
    show: true
    formType: '0'
    sortNum: '5'
    logicShowConfig: {}
  - wid: '33787'
    formWid: '2222'
    fieldType: '2'
    title: 你今天是否与疑似/确诊新冠肺炎患者有密切接触？
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 6
    colName: field006
    fieldItems:
      - itemWid: '78258'
        content: 否
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 6
    value: '78258'
    show: true
    formType: '0'
    sortNum: '6'
    logicShowConfig: {}
  - wid: '33788'
    formWid: '2222'
    fieldType: '2'
    title: 你今天是否有咳嗽、乏力等症状
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 7
    colName: field007
    fieldItems:
      - itemWid: '78260'
        content: 否
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 7
    value: '78260'
    show: true
    formType: '0'
    sortNum: '7'
    logicShowConfig: {}
  - wid: '33789'
    formWid: '2222'
    fieldType: '2'
    title: 你今天是否就诊或住院
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 8
    colName: field008
    fieldItems:
      - itemWid: '78262'
        content: 否
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 8
    value: '78262'
    show: true
    formType: '0'
    sortNum: '8'
    logicShowConfig: {}
  - wid: '33790'
    formWid: '2222'
    fieldType: '1'
    title: 如果就诊或住院，请填写你去的医院名称（注：未就诊、住院的不填）
    description: ''
    isRequired: false
    hasOtherItems: false
    sort: 9
    colName: field009
    fieldItems: []
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: '1'
      maxValue: '300'
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 9
    value: ''
    show: true
    formType: '0'
    sortNum: '9'
    logicShowConfig: {}
  - wid: '33791'
    formWid: '2222'
    fieldType: '2'
    title: 你是否被隔离，如果被隔离，请选择你的隔离方式
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 10
    colName: field010
    fieldItems:
      - itemWid: '78265'
        content: 否
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 10
    value: '78265'
    show: true
    formType: '0'
    sortNum: '10'
    logicShowConfig: {}
  - wid: '33792'
    formWid: '2222'
    fieldType: '1'
    title: 如果被隔离，请填写目前被隔离的详细地址（注：未被隔离的不填）
    description: ''
    isRequired: false
    hasOtherItems: false
    sort: 11
    colName: field011
    fieldItems: []
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: '1'
      maxValue: '300'
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 11
    value: ''
    show: true
    formType: '0'
    sortNum: '11'
    logicShowConfig: {}
  - wid: '33793'
    formWid: '2222'
    fieldType: '2'
    title: 目前是否在学校
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 12
    colName: field012
    fieldItems:
      - itemWid: '78268'
        content: 是
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 12
    value: '78268'
    show: true
    formType: '0'
    sortNum: '12'
    logicShowConfig: {}
  - wid: '33794'
    formWid: '2222'
    fieldType: '7'
    title: 目前你所在城市
    description: 注：省、市、区/县、具体地址，如江苏省徐州市泉山区
    isRequired: true
    hasOtherItems: false
    sort: 13
    colName: field013
    fieldItems: []
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 13
    value: 江苏省/徐州市/铜山区/
    show: true
    formType: '0'
    sortNum: '13'
    logicShowConfig: {}
  - wid: '33795'
    formWid: '2222'
    fieldType: '2'
    title: 今天是否有跨区域行程异动（注：指跨县及以上行政区域，徐州市内各区之间的交通活动不用填报）
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 14
    colName: field014
    fieldItems:
      - itemWid: '78270'
        content: 否
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 14
    value: '78270'
    show: true
    formType: '0'
    sortNum: '14'
    logicShowConfig: {}
  - wid: '33796'
    formWid: '2222'
    fieldType: '6'
    title: 如果行程有异动，请填写异动具体时间（注：未异动的不填）
    description: ''
    isRequired: false
    hasOtherItems: false
    sort: 15
    colName: field015
    fieldItems: []
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: '1'
      dateType: '0'
      pointTime: null
      minTime: '1900-01-01 00:00'
      maxTime: '2099-12-31 23:59'
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 15
    value: ''
    show: true
    formType: '0'
    sortNum: '15'
    logicShowConfig: {}
  - wid: '33797'
    formWid: '2222'
    fieldType: '7'
    title: 如果行程有异动，请填写行程异动目的地（注：未异动的不填）
    description: ''
    isRequired: false
    hasOtherItems: false
    sort: 16
    colName: field016
    fieldItems: []
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 16
    value: ''
    show: true
    formType: '0'
    sortNum: '16'
    logicShowConfig: {}
  - wid: '33798'
    formWid: '2222'
    fieldType: '1'
    title: 如果行程有异动，请填写异动原因、出行方式和具体车次等信息（未异动的不填）
    description: ''
    isRequired: false
    hasOtherItems: false
    sort: 17
    colName: field017
    fieldItems: []
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: '1'
      maxValue: '300'
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 17
    value: ''
    show: true
    formType: '0'
    sortNum: '17'
    logicShowConfig: {}
  - wid: '33799'
    formWid: '2222'
    fieldType: '2'
    title: "本人是否承诺以上所填报的全部内容属实、准确，不存在任何隐瞒、不实和遗漏之处\_"
    description: ''
    isRequired: true
    hasOtherItems: false
    sort: 18
    colName: field018
    fieldItems:
      - itemWid: '78272'
        content: 是
        imageUrl: ''
        isOtherItems: false
        contentExtend: ''
        otherItemType: '1'
        basicConfig: null
        showLogic: ''
        isAnswer: false
        score: null
        isSelected: 1
        selectCount: null
        totalCount: 0
    scoringRule: '-1'
    score: null
    answerContent: null
    basicConfig:
      minValue: null
      maxValue: null
      decimals: null
      dateFormatType: null
      dateType: null
      pointTime: null
      minTime: null
      maxTime: null
      extremeLabel: null
      level: null
      isReversal: null
      leftValue: null
      rightValue: null
      voteType: null
      voteMinValue: null
      voteMaxValue: null
    logicWid: 18
    value: '78272'
    show: true
    formType: '0'
    sortNum: '18'
    logicShowConfig: {}
uaIsCpadaily: true
latitude: 34.222758318126125
longitude: 117.1544060480875
